// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneWebApp.Models;

#nullable disable

namespace PhoneWebApp.Migrations
{
    [DbContext(typeof(PhoneContactContext))]
    partial class PhoneContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneWebApp.Models.PhoneContact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("PhoneContacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "123 Maple St, Springfield, IL",
                            Name = "Alice Johnson",
                            Note = "Friend from college",
                            PhoneNumber = "515-555-1234"
                        },
                        new
                        {
                            ContactId = 2,
                            Name = "Bob Smith",
                            PhoneNumber = "515-555-5678"
                        },
                        new
                        {
                            ContactId = 3,
                            Name = "Charlie Davis",
                            Note = "Work colleague",
                            PhoneNumber = "319-555-8765"
                        },
                        new
                        {
                            ContactId = 4,
                            Address = "456 Oak Ave, Lincoln, NE",
                            Name = "Diana Evans",
                            PhoneNumber = "712-555-4321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
